### PR TITLE
Fixed the funky shdDotobjFullbright shader gl_Positon = glPosition assign

### PR DESCRIPTION
**Pull request by JulianDicken**

### CODE REVIEW

**Comment by JujuAdams** [comment]
Looootta fluff here. Please strip it out and keep only the essential change in the shader.

**Comment by JulianDicken** [comment]
Oh yeah, didnt pay attention. Fixed.

**Comment by JujuAdams** [comment]
You've now reverted the actual change itself... I'll do it myself...

**Comment by JulianDicken** [comment]
God damn it I pushed the yyp not the vsh

**Pull request closed without merging**
